### ISSUE TITLE
No package.json in generated project

### ISSUE THREAD

**Issue by mattrossman** [lencx/create-xc-app#1]
When I run the line from the README:
```
npm init xc-app my-wasm-app --template wasm-react
```
the created `my-wasm-app` directory does not contain a `package.json`, so the subsequent `npm install` and `npm run dev` commands fail.

**Comment by mattrossman** [comment]
If I instead just use `npm init xc-app` and follow the prompts to select the react template, then it creates the package.json file

**Comment by lencx** [comment]
The command to create the specified template currently seems to be invalid. You can generate it by `npm init xc-app`.

**Comment by mattrossman** [comment]
Thanks, I'm really impressed by the speed of development once it's up and running. Didn't know Rust could build this fast!

Btw I think tweaking the logic here to not rely on the emoji would fix the command:
https://github.com/lencx/create-xc-app/blob/d00ce000012fce3fb659068310abc8ad8916b714/index.js#L125-L128

**Comment by lencx** [comment]
Thanks, I will review the code later. https://github.com/lencx/vite-plugin-rsw can get more information about the plugin.

**Comment by lencx** [comment]
The problem has been fixed, please try the following command again.

```bash
# npm 6.x
npm init xc-app my-wasm-app --template wasm-react

# npm 7+, extra double-dash is needed:
npm init xc-app my-wasm-app -- --template wasm-react
```
